Bước 4: Feature Engineering

Xử lý:

Skewness > / Inconsistent > / Missing > / Outlier >

Làm giàu đặc trưng (Feature Enrichment)

Biến đổi đặc trưng (Feature Transformation) >

Chọn đặc trưng (Feature Selection) >

Mã hóa đặc trưng (Feature Encoding)

Chuẩn hóa dữ liệu (Feature Scaling):

Normalization

Standardization

In [1]:
import pandas as pd
import re

data = pd.read_csv('/home/vophilong/Documents/Deep_learning/Dataset/dataset.csv')
display(data.head())

,EmailSend,EmailReply,SubjectSend,SubjectReply,From,To,DateSend,DateReply,Context
0,"Nikki, Thanks for the note and I hope your doi...",Hello hello! I was so worried that I had said ...,Portland,Re: Portland,bill.williams@enron.com,-nikole@excite.com,6/18/2001 22:44,6/19/2001 15:49,NaN
1,Jim Lokay Sales Representative British Parts I...,HI,Call when you receive this (no rush),RE: Call when you receive this (no rush),548@britishparts.com,michelle.lokay@enron.com,3/19/2002 8:30,3/19/2002 8:34,NaN
2,Congratulations! Have a good sleep.,Just woke up...thnx for your note. I believe t...,Thanks and,Re: Thanks and,louise.kitchen@enron.com,8774754543@skytel.com,1/15/2002 12:30,1/15/2002 16:29,NaN
3,Test,Call back : Geir.Solberg@enron.com|Test|Test,Test,Re: Test,geir.solberg@enron.com,8776519147@skytel.com,1/19/2002 10:55,1/19/2002 10:56,NaN
4,We are dropping a lot of marketers. It would b...,As shankman would say 'working ya',Marketers,RE: Marketers,8777865122@skytel.com,louise.kitchen@enron.com,1/21/2002 15:30,1/21/2002 15:44,NaN

In [2]:
# Chọn đặc trưng 
columns_to_keep = ['Context', 'EmailSend', 'EmailReply']
df_prep = data[columns_to_keep].copy()
print(f"[1] Kích thước ban đầu: {df_prep.shape[0]} dòng.")
# in ra 30 dòng đầu tiên để kiểm tra
display(df_prep.head(30))

[1] Kích thước ban đầu: 15377 dòng.

,Context,EmailSend,EmailReply
0,NaN,"Nikki, Thanks for the note and I hope your doi...",Hello hello! I was so worried that I had said ...
1,NaN,Jim Lokay Sales Representative British Parts I...,HI
2,NaN,Congratulations! Have a good sleep.,Just woke up...thnx for your note. I believe t...
3,NaN,Test,Call back : Geir.Solberg@enron.com|Test|Test
4,NaN,We are dropping a lot of marketers. It would b...,As shankman would say 'working ya'
5,NaN,What are they having?,Need you or John to step out. : Louise.Kitchen...
6,NaN,What is the situation with a lawsuit involving...,Solarc is the system used for NGLs etc - we do...
7,NaN,Did you get tg back to 1yr docs,Did not get a commitment. Just told them I tho...
8,NaN,What do you think happens if they require 2yrs?,50% or less of the current group. We have a ma...
9,NaN,We are going to have to work on making this mo...,"I understand. If I have too, I will dip into m..."
10,NaN,"And, because I waited so long, it should be do...",How are you doing Chris? I have been away for ...
11,"And, because I waited so long, it should be do...",How are you doing Chris? I have been away for ...,I am wonderful thank you very much. Where have...
12,How are you doing Chris? I have been away for ...,I am wonderful thank you very much. Where have...,I was on loan to EES since mid July.
13,I am wonderful thank you very much. Where have...,I was on loan to EES since mid July.,You lucky girl. Let tell me all the interestin...
14,I was on loan to EES since mid July.,You lucky girl. Let tell me all the interestin...,"Chris, I have the termination letter initialed..."
15,You lucky girl. Let tell me all the interestin...,"Chris, I have the termination letter initialed...","Early this afternoon would be fine, say around..."
16,"Chris, I have the termination letter initialed...","Early this afternoon would be fine, say around...",OK....see you then.
17,NaN,Please find attached the model for the TransPe...,James: Can we scale this down a bit? As I ment...
18,NaN,I trimmed down the model per your request. Let...,much better - even I can follow this one! than...
19,NaN,"Kevin, attached is the Sun Devil powerpoint pr...",Thanks for the quick turnaround. I will take a...
20,NaN,"The Sun Devil model is pretty big, over 2000kb...","can we summarize it into a smaller, more manag..."
21,NaN,Attached is a summary model for TW's Sun Devil...,Thanks. Let us start with this and add more la...
22,NaN,Attached is the Sun Devil model using the $911...,Why are not we using the lower capex number wi...
23,Attached is the Sun Devil model using the $911...,Why are not we using the lower capex number wi...,I sent the model that matches up with the info...
24,NaN,what other time either Tues pm or Wed am are y...,Anytime after 4 on Tuesday or anytime Wed. mor...
25,NaN,"If I can set it up, are you available for brea...",I can make it by 8.
26,"If I can set it up, are you available for brea...",I can make it by 8.,Panda has already scheduled other meetings aro...
27,I can make it by 8.,Panda has already scheduled other meetings aro...,where at?
28,Panda has already scheduled other meetings aro...,where at?,EB 1336
29,NaN,"Kevin, please review the attached and add any ...",i made some slight modifications.

In [3]:
# Xử lý missing value
df_prep['Context'] = df_prep['Context'].fillna("") # Điền giá trị rỗng cho các dòng bị thiếu trong cột 'Context'
# Xóa các dòng có giá trị thiếu trong cột 'EmailSend' hoặc 'EmailReply'
df_prep = df_prep.dropna(subset=['EmailSend', 'EmailReply'])
print(f" Kích thước sau khi xử lý missing value: {df_prep.shape[0]} dòng.")
display(df_prep.head(30))

 Kích thước sau khi xử lý missing value: 15377 dòng.

,Context,EmailSend,EmailReply
0,,"Nikki, Thanks for the note and I hope your doi...",Hello hello! I was so worried that I had said ...
1,,Jim Lokay Sales Representative British Parts I...,HI
2,,Congratulations! Have a good sleep.,Just woke up...thnx for your note. I believe t...
3,,Test,Call back : Geir.Solberg@enron.com|Test|Test
4,,We are dropping a lot of marketers. It would b...,As shankman would say 'working ya'
5,,What are they having?,Need you or John to step out. : Louise.Kitchen...
6,,What is the situation with a lawsuit involving...,Solarc is the system used for NGLs etc - we do...
7,,Did you get tg back to 1yr docs,Did not get a commitment. Just told them I tho...
8,,What do you think happens if they require 2yrs?,50% or less of the current group. We have a ma...
9,,We are going to have to work on making this mo...,"I understand. If I have too, I will dip into m..."
10,,"And, because I waited so long, it should be do...",How are you doing Chris? I have been away for ...
11,"And, because I waited so long, it should be do...",How are you doing Chris? I have been away for ...,I am wonderful thank you very much. Where have...
12,How are you doing Chris? I have been away for ...,I am wonderful thank you very much. Where have...,I was on loan to EES since mid July.
13,I am wonderful thank you very much. Where have...,I was on loan to EES since mid July.,You lucky girl. Let tell me all the interestin...
14,I was on loan to EES since mid July.,You lucky girl. Let tell me all the interestin...,"Chris, I have the termination letter initialed..."
15,You lucky girl. Let tell me all the interestin...,"Chris, I have the termination letter initialed...","Early this afternoon would be fine, say around..."
16,"Chris, I have the termination letter initialed...","Early this afternoon would be fine, say around...",OK....see you then.
17,,Please find attached the model for the TransPe...,James: Can we scale this down a bit? As I ment...
18,,I trimmed down the model per your request. Let...,much better - even I can follow this one! than...
19,,"Kevin, attached is the Sun Devil powerpoint pr...",Thanks for the quick turnaround. I will take a...
20,,"The Sun Devil model is pretty big, over 2000kb...","can we summarize it into a smaller, more manag..."
21,,Attached is a summary model for TW's Sun Devil...,Thanks. Let us start with this and add more la...
22,,Attached is the Sun Devil model using the $911...,Why are not we using the lower capex number wi...
23,Attached is the Sun Devil model using the $911...,Why are not we using the lower capex number wi...,I sent the model that matches up with the info...
24,,what other time either Tues pm or Wed am are y...,Anytime after 4 on Tuesday or anytime Wed. mor...
25,,"If I can set it up, are you available for brea...",I can make it by 8.
26,"If I can set it up, are you available for brea...",I can make it by 8.,Panda has already scheduled other meetings aro...
27,I can make it by 8.,Panda has already scheduled other meetings aro...,where at?
28,Panda has already scheduled other meetings aro...,where at?,EB 1336
29,,"Kevin, please review the attached and add any ...",i made some slight modifications.

In [4]:
#Biến đổi và làm sạch dữ liệu
def clean_email(text):
    if pd.isna(text):
        return ""
    # Loại bỏ các ký tự đặc biệt và số, chỉ giữ lại chữ cái và khoảng trắng
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    # Chuyển về chữ thường
    text = text.lower()
    # Chuẩn hóa inconsistent formatting (ví dụ: "Hello   World" -> "Hello World")
    text = re.sub(r'\s+', ' ', text).strip()
    #Loại bỏ các xuống dòng và tab
    text = re.sub(r'[\n\t]+', ' ', text)
    # loại bỏ các ký tự không in được
    text = re.sub(r'[^\x00-\x7F]+', '', text)
    # loại bỏ các ký tự lặp lại quá nhiều lần (ví dụ: "hiiiiii" -> "hii")
    text = re.sub(r'(.)\1{2,}', r'\1\1', text)
    return text
# Áp dụng cho cả 3 cột
for col in ['Context', 'EmailSend', 'EmailReply']:
    df_prep[col] = df_prep[col].apply(clean_email)
# Xem kích thước sau khi làm sạch và 30 dòng đầu tiên để kiểm tra
print(f" Kích thước sau khi làm sạch dữ liệu: {df_prep.shape[0]} dòng.")

display(df_prep.head(50))

 Kích thước sau khi làm sạch dữ liệu: 15377 dòng.

,Context,EmailSend,EmailReply
0,,nikki thanks for the note and i hope your doin...,hello hello i was so worried that i had said s...
1,,jim lokay sales representative british parts i...,hi
2,,congratulations have a good sleep,just woke upthnx for your note i believe that ...
3,,test,call back geirsolbergenroncomtesttest
4,,we are dropping a lot of marketers it would be...,as shankman would say working ya
5,,what are they having,need you or john to step out louisekitchenenro...
6,,what is the situation with a lawsuit involving...,solarc is the system used for ngls etc we do n...
7,,did you get tg back to yr docs,did not get a commitment just told them i thou...
8,,what do you think happens if they require yrs,or less of the current group we have a market ...
9,,we are going to have to work on making this mo...,i understand if i have too i will dip into my ...
10,,and because i waited so long it should be done...,how are you doing chris i have been away for a...
11,and because i waited so long it should be done...,how are you doing chris i have been away for a...,i am wonderful thank you very much where have ...
12,how are you doing chris i have been away for a...,i am wonderful thank you very much where have ...,i was on loan to ees since mid july
13,i am wonderful thank you very much where have ...,i was on loan to ees since mid july,you lucky girl let tell me all the interesting...
14,i was on loan to ees since mid july,you lucky girl let tell me all the interesting...,chris i have the termination letter initialed ...
15,you lucky girl let tell me all the interesting...,chris i have the termination letter initialed ...,early this afternoon would be fine say around ...
16,chris i have the termination letter initialed ...,early this afternoon would be fine say around ...,oksee you then
17,,please find attached the model for the transpe...,james can we scale this down a bit as i mentio...
18,,i trimmed down the model per your request let ...,much better even i can follow this one thanks ...
19,,kevin attached is the sun devil powerpoint pre...,thanks for the quick turnaround i will take a ...
20,,the sun devil model is pretty big over kb i am...,can we summarize it into a smaller more manage...
21,,attached is a summary model for tws sun devil ...,thanks let us start with this and add more lat...
22,,attached is the sun devil model using the mm c...,why are not we using the lower capex number wi...
23,attached is the sun devil model using the mm c...,why are not we using the lower capex number wi...,i sent the model that matches up with the info...
24,,what other time either tues pm or wed am are y...,anytime after on tuesday or anytime wed morning
25,,if i can set it up are you available for break...,i can make it by
26,if i can set it up are you available for break...,i can make it by,panda has already scheduled other meetings aro...
27,i can make it by,panda has already scheduled other meetings aro...,where at
28,panda has already scheduled other meetings aro...,where at,eb
29,,kevin please review the attached and add any d...,i made some slight modifications
30,kevin please review the attached and add any d...,i made some slight modifications,thanks that looks great
31,,kim i was hoping to catch up with you after st...,kevin would you have some time today or tomorr...
32,,kim rod has asked me to fill in for him at a m...,kevin we can meet at pm in eb thanks kim
33,kim rod has asked me to fill in for him at a m...,kevin we can meet at pm in eb thanks kim,thanks i will be there
34,,kim do you have any write ups on the above pro...,kevin we will write these up and send them to ...
35,,kevin for trans pecos we have a couple of slid...,let us use the fact sheet for now i was hoping...
36,kevin for trans pecos we have a couple of slid...,let us use the fact sheet for now i was hoping...,i will send the fact sheet now however i am ha...
37,,do you want to premeet are we still scheduled ...,pre meeting tomorrow at in danny steve eric yo...
38,,kevin donna and i are working on the floor pla...,kim i appreciate you moving so quickly on this...
39,,response number it would be for myself davis a...,thanks we will make room for the three of you ...
40,,is this in addition to the one with dan at,yes the is the prep meeting to the stan meetin...
41,,i will call you monday morning to discuss what...,the mlp discussions have been on using norther...
42,,kevin due to stans floor meeting at are you av...,yes where
43,kevin due to stans floor meeting at are you av...,yes where,let us meeting in eb thanks kim
44,,attached is redlined draft plese see changes t...,thanks so much for your quick turnaround rob k...
45,,pie chart slide for aznm and nev shows the sou...,it is my understanding from kevin hyatt that i...
46,pie chart slide for aznm and nev shows the sou...,it is my understanding from kevin hyatt that i...,thanks that is what i was hoping it was headin...
47,it is my understanding from kevin hyatt that i...,thanks that is what i was hoping it was headin...,good luck
48,,do we need to have our meeting today i could s...,i will get back with you as soon as possible m...
49,,attached is the spreadsheet from facility plan...,thanks i was more interested in the economics ...

In [9]:
# Loại bỏ nhiễu

df = df_prep.copy()

# Xử lý Skewness và Outliers bằng cách cắt tỉa độ dài của EmailSend và EmailReply
df = df[
    (df['EmailSend'].str.len().between(10, 1500)) &
    (df['EmailReply'].str.len().between(100, 1500))
]

# 2. Loại bỏ các cặp Email quá giống nhau (paraphrase)
from difflib import SequenceMatcher

def is_similar(a, b):
    return SequenceMatcher(None, a, b).ratio() > 0.8

df = df[~df.apply(lambda x: is_similar(x['EmailSend'], x['EmailReply']), axis=1)]

# 3. Giữ lại các phản hồi có ý nghĩa
df = df[
    df['EmailReply'].str.contains(r"\b(I|we|yes|no|thank|sorry)\b", case=False, regex=True)
]

# Kết quả cuối
df_clean = df.copy()

# Thống kê
dropped_rows = df_prep.shape[0] - df_clean.shape[0]

print(f"Đã cắt tỉa {dropped_rows} dòng dữ liệu nhiễu (Outliers).")
print(f"Kích thước sau khi lọc: {df_clean.shape[0]} dòng.")

display(df_clean.head(30))

/tmp/ipykernel_10868/2286964091.py:21: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df['EmailReply'].str.contains(r"\b(I|we|yes|no|thank|sorry)\b", case=False, regex=True)

Đã cắt tỉa 8982 dòng dữ liệu nhiễu (Outliers).
Kích thước sau khi lọc: 6395 dòng.

,Context,EmailSend,EmailReply
2,,congratulations have a good sleep,just woke upthnx for your note i believe that ubs was the best fit and the best bid excluding the retention i hope e...
6,,what is the situation with a lawsuit involving solarc,solarc is the system used for ngls etc we do not plan to convey it into netco in terms of the court case the whole t...
7,,did you get tg back to yr docs,did not get a commitment just told them i thought it would be impossible louisekitchenenroncomre solarcdid you get t...
8,,what do you think happens if they require yrs,or less of the current group we have a market of year x so we will need more cash for less people we may need our sp...
9,,we are going to have to work on making this money work several things have to balance out,i understand if i have too i will dip into my money i think the requests are reasonable and fair with respect to ind...
10,,and because i waited so long it should be done in a great big hurry,how are you doing chris i have been away for awhilejust wanted to let you know that i am working on it
14,i was on loan to ees since mid july,you lucky girl let tell me all the interesting stuff that is going on,chris i have the termination letter initialed by gerald nemec in legal let me know when i can come and bring it to y...
17,,please find attached the model for the transpecos project james,james can we scale this down a bit as i mentioned to kevin hyatt yesterday we just need a slimmed down version for t...
18,,i trimmed down the model per your request let me know if this is ok thanks james,much better even i can follow this one thanks this will allow them to get up to speed much quicker kevin
20,,the sun devil model is pretty big over kb i am not sure how well it will email but we can try it we may want to send...,can we summarize it into a smaller more manageable format they probabaly do not need this much detail to get started...
26,if i can set it up are you available for breakfast with panda on wed morning how early regards kevin,i can make it by,panda has already scheduled other meetings around ours so they cannot move our time the will likely be in our office...
31,,kim i was hoping to catch up with you after stans meeting to discuss tw financing arrangements their is still a very...,kevin would you have some time today or tomorrow to discuss this also we should rally with kevin hyatt to discuss hi...
36,kevin for trans pecos we have a couple of slides with a fact sheet prepared that we used in the presentation with st...,let us use the fact sheet for now i was hoping to get something to them in the next hours,i will send the fact sheet now however i am happy to create whatever you need to help get this money i will send it ...
38,,kevin donna and i are working on the floor plan we have you slotted to move with us although we do not know exactly ...,kim i appreciate you moving so quickly on this however before we do anything i need to see what you are proposing an...
39,,response number it would be for myself davis and my assistant terri bachand,thanks we will make room for the three of you we are looking at moving either to or we have tentative floor plans fo...
40,,is this in addition to the one with dan at,yes the is the prep meeting to the stan meeting danny wants us to look at project financing vs mlp if you get a chan...
41,,i will call you monday morning to discuss what is the status of the pemex discussions when dan mentions mlp is he re...,the mlp discussions have been on using northern border regarding kmi mark and i met with them before xmas to see whe...
44,,attached is redlined draft plese see changes to the history and customers contracts sections requested,thanks so much for your quick turnaround rob kilmer is adding the regulatory section and we should have that tomorro...
57,the q describes rawhide although it does not list investments it does reference domestic and international assets i ...,this would be an enron deal and we just have to get over the hurdles here,dan boyle mentioned that today is the deadline for the rawhide amendment if we do not get it could be trouble
63,,either robert guthrie or greek rice,i have included paul cherry gary smith jim bouillion greek rice phil lowry and three from mkms team i went through t...
69,,shelley do you have any information on project max that we could use in the business plan for nng,there are a couple of slides in the recent bank package nng prepared and a few more slides in the original budget pa...
71,,shelley reading an old nng offering circular and it refers to a skyline proposal did this get final approval from fe...,skyline refers to added seasonality that nng proposed to add to its rates the rate case settlement represented a com...
74,,i think my exact words were the best not one of the best,pressure to finish my review my husband is in indonesia on business so do not be surprised if i reply in the middle ...
75,,shelley welcome back i was wondering if you had minutes today to discuss nngs major customers from a strategic persp...,hi i am here just barely though my sinus infection is back can we get together in my office the less elevator riding...
81,,steve if i can get you current polling data that indicate vulnerability on the part of brown would the pac reconside...,we can always reconsider in the sense of providing support to someone else but the money to brown is out the door i ...
82,steve if i can get you current polling data that indicate vulnerability on the part of brown would the pac reconside...,we can always reconsider in the sense of providing support to someone else but the money to brown is out the door i ...,i am not concerned with the brown money my focus is on possibly dislodging money for orlando i will try and arrange ...
83,,tom lamphier and wallis had orig during the st qtr but was classified as gas assets and not middle mkt texas these t...,please forward the information to eddie leschber and laynie east i know the origination was classified as gas assets...
84,,christian want you to have not only a smmoth but enjoyable transition to the yous i asked anne labbe to send you som...,hi mike thanks for the message we have received already some further information regarding houses and schools in hou...
85,,mike put me down for two me and the girl friend would love to go to the game let me know if you need me to do anythi...,jon two you are done looking forward to a great time me you jose my wife mary jo and your gal will enjoy witnessing ...
86,,gerald it was fun getting together friday here is the info on jennifer jenniferdsandersusandersencom office mike,thanks for the info mike i will give her a call i had a blast on friday we will have to do a happy hour again soon m...

In [10]:
# Định dạng dữ liệu đầu vào
df_clean['Input_Text'] = "context: " + df_clean['Context'] + " | email: " + df_clean['EmailSend'] # Tạo cột mới 'Input_Text' bằng cách kết hợp 'Context' và 'EmailSend'
df_clean['Output_Text'] = df_clean['EmailReply']# Tạo cột mới 'Output_Text' bằng cách sao chép nội dung từ 'EmailReply'
# Chọn lại các cột cần thiết
final_dataset = df_clean[['Input_Text', 'Output_Text']].copy()
# Xem kích thước cuối cùng và 30 dòng đầu tiên để kiểm tra
print(f" Kích thước cuối cùng sau khi mã hóa và chuẩn hóa: {final_dataset.shape[0]} dòng.")
pd.set_option('display.max_colwidth', 120) # Mở rộng cột để dễ đọc
display(final_dataset.head(30))

 Kích thước cuối cùng sau khi mã hóa và chuẩn hóa: 6395 dòng.

,Input_Text,Output_Text
2,context: | email: congratulations have a good sleep,just woke upthnx for your note i believe that ubs was the best fit and the best bid excluding the retention i hope e...
6,context: | email: what is the situation with a lawsuit involving solarc,solarc is the system used for ngls etc we do not plan to convey it into netco in terms of the court case the whole t...
7,context: | email: did you get tg back to yr docs,did not get a commitment just told them i thought it would be impossible louisekitchenenroncomre solarcdid you get t...
8,context: | email: what do you think happens if they require yrs,or less of the current group we have a market of year x so we will need more cash for less people we may need our sp...
9,context: | email: we are going to have to work on making this money work several things have to balance out,i understand if i have too i will dip into my money i think the requests are reasonable and fair with respect to ind...
10,context: | email: and because i waited so long it should be done in a great big hurry,how are you doing chris i have been away for awhilejust wanted to let you know that i am working on it
14,context: i was on loan to ees since mid july | email: you lucky girl let tell me all the interesting stuff that is g...,chris i have the termination letter initialed by gerald nemec in legal let me know when i can come and bring it to y...
17,context: | email: please find attached the model for the transpecos project james,james can we scale this down a bit as i mentioned to kevin hyatt yesterday we just need a slimmed down version for t...
18,context: | email: i trimmed down the model per your request let me know if this is ok thanks james,much better even i can follow this one thanks this will allow them to get up to speed much quicker kevin
20,context: | email: the sun devil model is pretty big over kb i am not sure how well it will email but we can try it ...,can we summarize it into a smaller more manageable format they probabaly do not need this much detail to get started...
26,context: if i can set it up are you available for breakfast with panda on wed morning how early regards kevin | emai...,panda has already scheduled other meetings around ours so they cannot move our time the will likely be in our office...
31,context: | email: kim i was hoping to catch up with you after stans meeting to discuss tw financing arrangements th...,kevin would you have some time today or tomorrow to discuss this also we should rally with kevin hyatt to discuss hi...
36,context: kevin for trans pecos we have a couple of slides with a fact sheet prepared that we used in the presentatio...,i will send the fact sheet now however i am happy to create whatever you need to help get this money i will send it ...
38,context: | email: kevin donna and i are working on the floor plan we have you slotted to move with us although we d...,kim i appreciate you moving so quickly on this however before we do anything i need to see what you are proposing an...
39,context: | email: response number it would be for myself davis and my assistant terri bachand,thanks we will make room for the three of you we are looking at moving either to or we have tentative floor plans fo...
40,context: | email: is this in addition to the one with dan at,yes the is the prep meeting to the stan meeting danny wants us to look at project financing vs mlp if you get a chan...
41,context: | email: i will call you monday morning to discuss what is the status of the pemex discussions when dan me...,the mlp discussions have been on using northern border regarding kmi mark and i met with them before xmas to see whe...
44,context: | email: attached is redlined draft plese see changes to the history and customers contracts sections requ...,thanks so much for your quick turnaround rob kilmer is adding the regulatory section and we should have that tomorro...
57,context: the q describes rawhide although it does not list investments it does reference domestic and international ...,dan boyle mentioned that today is the deadline for the rawhide amendment if we do not get it could be trouble
63,context: | email: either robert guthrie or greek rice,i have included paul cherry gary smith jim bouillion greek rice phil lowry and three from mkms team i went through t...
69,context: | email: shelley do you have any information on project max that we could use in the business plan for nng,there are a couple of slides in the recent bank package nng prepared and a few more slides in the original budget pa...
71,context: | email: shelley reading an old nng offering circular and it refers to a skyline proposal did this get fin...,skyline refers to added seasonality that nng proposed to add to its rates the rate case settlement represented a com...
74,context: | email: i think my exact words were the best not one of the best,pressure to finish my review my husband is in indonesia on business so do not be surprised if i reply in the middle ...
75,context: | email: shelley welcome back i was wondering if you had minutes today to discuss nngs major customers fro...,hi i am here just barely though my sinus infection is back can we get together in my office the less elevator riding...
81,context: | email: steve if i can get you current polling data that indicate vulnerability on the part of brown woul...,we can always reconsider in the sense of providing support to someone else but the money to brown is out the door i ...
82,context: steve if i can get you current polling data that indicate vulnerability on the part of brown would the pac ...,i am not concerned with the brown money my focus is on possibly dislodging money for orlando i will try and arrange ...
83,context: | email: tom lamphier and wallis had orig during the st qtr but was classified as gas assets and not middl...,please forward the information to eddie leschber and laynie east i know the origination was classified as gas assets...
84,context: | email: christian want you to have not only a smmoth but enjoyable transition to the yous i asked anne la...,hi mike thanks for the message we have received already some further information regarding houses and schools in hou...
85,context: | email: mike put me down for two me and the girl friend would love to go to the game let me know if you n...,jon two you are done looking forward to a great time me you jose my wife mary jo and your gal will enjoy witnessing ...
86,context: | email: gerald it was fun getting together friday here is the info on jennifer jenniferdsandersusandersen...,thanks for the info mike i will give her a call i had a blast on friday we will have to do a happy hour again soon m...

In [11]:
# Lưu dataset đã làm sạch và mã hóa vào file CSV mới
final_dataset.to_csv('/home/vophilong/Documents/Deep_learning/DoAn_Email/final_dataset.csv', index=False)
print("Đã lưu dataset đã làm sạch và mã hóa vào file 'final_dataset.csv'.")

Đã lưu dataset đã làm sạch và mã hóa vào file 'final_dataset.csv'.